services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 2s
      timeout: 20s
      retries: 10
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    

  bot:
    build: .
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

    